### ISSUE TITLE
GITHUB to JIRA test #0010 (new title not shown in GH)

### ISSUE THREAD

**Issue by JamesAnthonyPino** [nasa/earthdata-search-test-config#27]
This is an issue reported in GH. We should see this as a new Story in the EDSC Test project in JIRA.

**Comment by earthdata-tasktop** [comment]
(Comment from earthdata-tasktop):

This is a comment that should NOT appear in GH.

**Comment by earthdata-tasktop** [comment]
(Comment from earthdata-tasktop):

This is a comment that SHOULD appear in GH since the Story is now approved.

**Comment by earthdata-tasktop** [comment]
(Comment from earthdata-tasktop):

This issue has now been fixed and should now show as closed in GH.
