### ISSUE TITLE
JIRA BUG to GITHUB ISSUE #0008 (updated title in JIRA)

### ISSUE THREAD

**Issue by earthdata-tasktop** [nasa/earthdata-search-test-config#42]
Test

**Comment by earthdata-tasktop** [comment]
(Comment from earthdata-tasktop):

This should now be seen in GH!

**Comment by JamesAnthonyPino** [comment]
This comment should be seen in JIRA!

**Comment by earthdata-tasktop** [comment]
(Comment from earthdata-tasktop):

Now in deferred state.

**Comment by earthdata-tasktop** [comment]
(Comment from earthdata-tasktop):

Now in progress.

**Comment by earthdata-tasktop** [comment]
(Comment from earthdata-tasktop):

FAILED. This should still be open in GH.

**Comment by earthdata-tasktop** [comment]
(Comment from earthdata-tasktop):

Submit for peer review.

**Comment by earthdata-tasktop** [comment]
(Comment from earthdata-tasktop):

Pass!

**Comment by earthdata-tasktop** [comment]
(Comment from earthdata-tasktop):

pass internally.

**Comment by earthdata-tasktop** [comment]
(Comment from earthdata-tasktop):

pass externally.

**Comment by earthdata-tasktop** [comment]
(Comment from earthdata-tasktop):

Complete. This should now be shown as closed in GH.

**Comment by JamesAnthonyPino** [comment]
This is now closed in GH. Will this appear in JIRA?
